### ISSUE TITLE
Any issues putting an nginx server in front of the load balancer?

### ISSUE THREAD

**Issue by elie222** [zodern/mup-aws-beanstalk#101]
We have a legacy set up and have an nginx server we'd like to keep running. We are using it to proxy to the load balancer created using this repository.

It seemed to be working okay the past few weeks but recently the site has become unreachable.

This is a sample error log:

```
[error] 2165#0: *71703 upstream timed out (110: Connection timed out) while connecting to upstream, client: 31.xxx.xx.x, server: example.com, request: "POST /graphql HTTP/1.1", upstream: "http://xx.xx.xxx.xx:80/graphql", host: "example.com"
```

Any idea why this is happening? The site has very little traffic atm. The Meteor servers seem fine in Monti APM and when I go to the Elastic Beanstalk url directly it works fine even with when the site is down. Any ideas?

**Comment by zodern** [comment]
I can reopen the issue if there are still any questions related to this.
