### ISSUE TITLE
Suggestion about single-thread apps

### ISSUE THREAD

**Issue by joaocarloscabral** [zodern/mup-aws-beanstalk#108]
Hello,

Following the logic that node applications are single threads, does it make sense to run multiple instances on the same machine to take advantage of multiple cores?

For example, if I use a server with 4 cpus, to make the best use of resources, would it be interesting to run 3 instances of the application (one per cpu) and leave a cpu free for other OS operations?

I'm quite a beginner with devops, but would it be possible to create such an environment using EBS and mup?
If this theory makes sense, what do you think of this suggestion and create this possibility in this plugin?
Thank you.

**Comment by zodern** [comment]
Some apps do take advantage of multiple  cores using workers, or other methods. This plugin relies on AWS Elastic Beanstalk for deciding where the app runs, so it is unlikely we will implement running multiple instances of the app on a server unless AWS Elastic Beanstalk does first.
