### ISSUE TITLE
mup.js 'buildLocation' path used differently by mup and meteor build.

### ISSUE THREAD

**Issue by priyankkapasi** [zodern/mup-aws-beanstalk#109]
Hello,

I came across this issue when I realised that new version of my meteor app was not being deployed, only the old build (built manually initially in the build path) wrapped in a new bundled zip was deployed. 

My high level Meteor app folder structure is: (apologies if my representation of directory tree is not up to expectations!)

```
-app-folder
--.meteor
--.deploy
---staging
----mup.js
----settings..json
---prod
----mup.js
----settings.json
--client
--server
--package.json
-bundle
```

In my _`staging/mup.js`_ file, I have:
```js
module.exports = {
  app: {
      // Tells mup that the AWS Beanstalk plugin will manage the app
      type: 'aws-beanstalk',
      name: 'app-staging',
      path: '../../'
      ... 
      ...
 buildOptions: {
        // Default is true
        serverOnly: true,
        debug: false,
        buildLocation: '../../../build',
        mobileSettings: {},
        server: 'http://app.com',
        allowIncompatibleUpdates: false,
        executable: 'meteor'
      },
```
Note: I am using MacOS

Now what happens is that, when I run `mup deploy` in _.deploy/staging_ , `meteor build` generates a bundle (folder) 3 levels up from the root folder. But, mup expects the bundle folder to be 3 level up from the mup.js file (ie. the last folder in the tree above).

Due to this, mup throws an error when it tries to copy its package.json file to bundle folder, because bundle folder is not present!

Am I doing anything wrong? Any pointers will be helpful!

Thanks!

**Comment by priyankkapasi** [comment]
Found out what I was doing incorrectly. Instead of running `mup deploy` from inside the _.deploy/staging_ folder, I passed the mup.js and settings as parameters (using --config and --settings) by running `mup deploy` from the root.

**Comment by zodern** [comment]
Using a relative path will be fixed in the next version of Meteor Up. For backwards compatibility I will probably make it relative to the current working directory, and Mup 2 will change all paths to be relative to the config.
