### ISSUE TITLE
mup reconfig -> Following services are not running: proxy.

### ISSUE THREAD

**Issue by gerwinbrunner** [zodern/mup-aws-beanstalk#115]
Hi,

just running the `mup reconfig` command leads to a 

the EC2 instance going to the `Following services are not running: proxy` state.

Has anybody else that issue? Any hints what could go wrong here?

P.S.:
When I do a `reboot` on that specific instance via the aws console then the instance comes back up and all is good and goes to green. Very wired and annoying... Any ideas why this is happening?

**Comment by gerwinbrunner** [comment]
Anybody got an idea why this is happening?

**Comment by gerwinbrunner** [comment]
Any hints?

**Comment by gerwinbrunner** [comment]
@zodern Got any idea on this?

**Comment by zodern** [comment]
In the elastic beanstalk console, you can request the full logs. If you download the logs and look at the nginx logs it should show why it is not running.
