### ISSUE TITLE
Look into updating config and version at the same time

### ISSUE THREAD

**Issue by zodern** [zodern/mup-aws-beanstalk#119]
Sometimes both the env vars and the app version need to be updated together. Beanstalk's documentation seem to indicate this isn't possible, but it would be worth looking into this further since it would improve deployment speed and reliability.

**Comment by gerwinbrunner** [comment]
Is there any update on this topic? 
I may be able to help and create a PR for this if you could point me to the area where I should start investigating.

**Comment by zodern** [comment]
I tried it a few months ago, and it does seem to work. I must have misunderstood Beanstalk's documentation.

There are potentially two updates done during a deploy:
1) [Update the env in the `reconfig` command](https://github.com/zodern/mup-aws-beanstalk/blob/0bc7a0e4e862e1f0c1e04231e983e72a4461110a/src/command-handlers.js#L532-L540)
2) [Update version when deploying](https://github.com/zodern/mup-aws-beanstalk/blob/0bc7a0e4e862e1f0c1e04231e983e72a4461110a/src/command-handlers.js#L262-L265)

This issue was for somehow doing it all at the same time when deploying.
