### ISSUE TITLE
Error validating ssl

### ISSUE THREAD

**Issue by raphaelarias** [zodern/mup-aws-beanstalk#12]
Hi.

I tried to execute a command and got an exception:
<img width="1156" alt="screen shot 2018-01-23 at 6 06 54 pm" src="https://user-images.githubusercontent.com/5008166/35270200-7ddf1df0-0082-11e8-84a7-518032af5708.png">

We have created the certificate directly in the AWS console, so maybe the exception happened because of that.

**Comment by zodern** [comment]
What version of the plugin are you using?

**Comment by raphaelarias** [comment]
The latest one, the one you released that supports AWS settings.

**Comment by zodern** [comment]
Version 0.4.0 is now available with this fixed.
