### ISSUE TITLE
AWS: Environment named *** is in an invalid state for this operation. Must be Ready

### ISSUE THREAD

**Issue by gaurav-github31** [zodern/mup-aws-beanstalk#125]
I get a message when I am trying to deploy my node app on EC2 using Elastic Beanstalk.

Configuring Beanstalk Environment
AWS: Environment named *** is in an invalid state for this operation. Must be Ready

I am unable to deploy. The server status is running, no warnings.

And ElasticBean Enviroment health is Severe

My experience is very limited at this point. How can I resolve this?

**Comment by zodern** [comment]
This should be fixed in 0.7. More details are in #142
