### ISSUE TITLE
Node 14

### ISSUE THREAD

**Issue by paulincai** [zodern/mup-aws-beanstalk#126]
Hi, anyone had any success with deploying a beta of Meteor 2.3? This requires an Amazon Linux 2 machine but I don't really get it how to request a specific container for Node 14. 
Using
```
{
        namespace: 'aws:elasticbeanstalk:container:nodejs',
        option: 'NodeVersion',
        value: '14.17.0'
      },

``` results in error since deployment goes by default with Linux 1 which is limited to Node 12.22.1

**Comment by paulincai** [comment]
Ok, I located the following code in src/command-handlers.js (around line 135), updated with a SolutionStackName, rebuilt and deployed in my project. All ok.

```
 if (!Applications.find(app => app.ApplicationName === appName)) {
    const params = {
      ApplicationName: appName,
      Description: `App "${appConfig.name}" managed by Meteor Up`,
      SolutionStackName: '64bit Amazon Linux 2 v5.4.1 running Node.js 14'
    };

    await beanstalk.createApplication(params).promise();
    console.log('  Created Beanstalk application');
  }
```

**Comment by s7dhansh** [comment]
@paulincai Is that a code change only or do we need to create a SolutionStack in AWS?
If it is just a code change, can you kindly send a PR so that @zodern may merge it.

**Comment by jamauro** [comment]
I tried inserting `SolutionStackName` as described above and I get this error when running `mup deploy` `UnexpectedParameter: Unexpected key 'SolutionStackName' found in params`.

@paulincai any ideas?

**Comment by jamauro** [comment]
In case someone else comes across this, here's a proposed solution: https://github.com/zodern/mup-aws-beanstalk/pull/133. It should work for future Node versions too (unless Amazon changes their naming scheme again :)
