### ISSUE TITLE
Deploy with the new Amazon AL2 Node images

### ISSUE THREAD

**Issue by gerwinbrunner** [zodern/mup-aws-beanstalk#127]
Hi,

when I deploy an app to AWS it uses the Node.js running on 64bit Amazon Linux/4.17.7 base image.
This image is now deprecated by Amazon and it is recommended to use the new AL2 Node images.

How could this be done with mup-aws-beanstalk deployments? 

Would you have a hint where to start to do this? Thanks!

**Comment by gerwinbrunner** [comment]
@zodern Any idea on this topic?

**Comment by jamauro** [comment]
@gerwinbrunner take a look here: https://github.com/zodern/mup-aws-beanstalk/issues/126

That'a a temporary fix. The code base needs to be updated with either this pull request or another solution: https://github.com/zodern/mup-aws-beanstalk/pull/128

**Comment by jamauro** [comment]
Here's another solution: https://github.com/zodern/mup-aws-beanstalk/pull/133. I wasn't having luck with the one proposed in #128.

**Comment by zodern** [comment]
The platforms that use Amazon Linux 2 have a number of differences compared to the older platforms. I published a beta that should add support for Amazon Linux 2. There are more details in #142. Please try it and let me know if you encounter any issues.

**Comment by zodern** [comment]
The second beta of 0.7.0 fully supports AL2.
