### ISSUE TITLE
Health Check failing (4xx): Severe status

### ISSUE THREAD

**Issue by MarceloPrado** [zodern/mup-aws-beanstalk#13]
Hi, first of all, thanks for this AMAZING plugin
I've been using mup with Digital Ocean for a while now and this new plugin solved all kinds of issues I had.

I've deploy my production web app but I'm constantly seeing a severe status on my instances. The cause of the status is: 99.0 % of the requests are erroring with HTTP 4xx.

I believe this is related to the way Beanstalk tries to connect with the meteor application via TCP protocol. I've read that it's possible to set an `Application Healthcheck URL`, via `aws:elasticbeanstalk:application` namespace. 

Is this the correct way to solve it?

**Comment by zodern** [comment]
The plugin should set the health check path to `/aws-health-check-3984729847289743128904723`, which uses [this server](https://github.com/zodern/mup-aws-beanstalk/blob/master/src/assets/health-check.js).
Does the app's logs have any lines starting with `[HealthCheck]`?

**Comment by MarceloPrado** [comment]
The server is running without any issues. When I manually GET this path, it returns `Success`, with status 200.

I requested all logs and searched for `HealthCheck`, but I couldn't find any results. My guess is that Beanstalk Healthcheck URL isn't set to `/aws-health-check-3984729847289743128904723`.

**Comment by MarceloPrado** [comment]
I'm still fighting with this one. I deployed a new application to make the error go away. It worked for a while. But after a new deploy today, the warning `93.3 % of the requests are erroring with HTTP 4xx.` started to appear again. 

It's not a problem with my application, though. It runs perfectly on the new instances.

**Comment by zodern** [comment]
I will add more logging in the next version to help find the cause.

**Comment by MarceloPrado** [comment]
Thanks! I'll try my best to help you out.

**Comment by zodern** [comment]
I released 0.5.0. It has [more logging](https://github.com/zodern/mup-aws-beanstalk/commit/eab4ad954af706ec9a839faa78a7fee70e2ae027) which should help see what the problem is.

**Comment by MarceloPrado** [comment]
Ok, this is weird. After using the 0.5.0, the logs says the HealthChek is working as expected.

Here's the last logs from `nodejs.log` file
```
[HealthCheck] Wed Mar 07 2018 13:52:43 GMT+0000 (UTC): Received health check request
[HealthCheck] Wed Mar 07 2018 13:52:43 GMT+0000 (UTC): Health check succeeded
```

But, in AWS Beanstalk Console, [here's](https://www.dropbox.com/s/l3b99pgv2gz5s7s/Screenshot%202018-03-07%2011.02.17.png?dl=0) what I see.

I'm suspecting it has something to do with HealthCheck URL being empty. Look at [this](https://www.dropbox.com/s/e3ta0mso4np7qks/Screenshot%202018-03-07%2011.06.45.png?dl=0) screenshot from Beanstalk Console Configuration page.

**Comment by zodern** [comment]
> I'm suspecting it has something to do with HealthCheck URL being empty. Look at this screenshot from Beanstalk Console Configuration page.

It should be empty. If you go to ec2, select `Target Groups` beneath Load Balancing on the left, select the group beanstalk created, and click the Health checks tab, it should be set there.

**Comment by MarceloPrado** [comment]
Yep, it's set. If I go to that path, it comes as expected (200 - Success).

**Comment by zodern** [comment]
In the `Targets` and `Monitoring` tabs for the target group, does it say the targets are healthy?

**Comment by MarceloPrado** [comment]
In `Targets`, instance is healthy.
In `Monitoring` tab, though, CloudWatch seems to be capturing a LOT more 4xx than 2xx. [Here's](https://www.dropbox.com/s/omnxbbherlqbdik/cloudwatch%20graphs.png?dl=0) a comparison between both of them in the last 6 hours.
