### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by jamauro** [zodern/mup-aws-beanstalk#130]
In the `eb-engine.log` 

```
An error occurred during execution of command [app-deploy] - [StageApplication]. 
Stop running the command.
Error: chown /var/app/staging/programs/server/npm/node_modules/meteor/activitree_push/node_modules/protobufjs/.node_modules-garbage-1d9fzmw.qib4/@types: no such file or directory 
```

Any ideas how to resolve this?

**Comment by paulincai** [comment]
Hi, will be waiting on your input on this: https://github.com/activitree/meteor-push/issues/39#issuecomment-891710186

**Comment by jamauro** [comment]
I think this bug is specific to the other package not mup-aws-beanstalk. Closing.
