### ISSUE TITLE
nvm: command not found

### ISSUE THREAD

**Issue by jamauro** [zodern/mup-aws-beanstalk#131]
In `web.stdout.log` I'm seeing `./start.sh: line 8: nvm: command not found`.

Any ideas what might be causing this? I'm not sure if it matters but I did edit the `command-handlers.js` file so that I could deploy on Amazon's supported Node platform `64bit Amazon Linux 2 v5.4.4 running Node.js 14`

**Comment by jamauro** [comment]
Turns out this wasn't preventing deployment but still pretty strange.

**Comment by zodern** [comment]
This is caused by using Amazon Linux 2. Version 0.7 should fix using it. If you want to try the beta, the details are in #142.
