### ISSUE TITLE
What is the Root username used to create the instances?

### ISSUE THREAD

**Issue by Roshdy** [zodern/mup-aws-beanstalk#143]
I'm trying to access my instance through aws Connect
It requires root username

> Connect using a custom user name, or use the default user name root for the AMI used to launch the instance.

My instances don't have any `key-pair` so i can't access them using `SSH`

Please help

**Comment by tanutapi** [comment]
In your `mup.js`, you can specify your key-pair configuration. But first, you must create your key-pair first.

app: {
  ...
  customBeanstalkConfig: [
      {
        namespace: 'aws:autoscaling:launchconfiguration',
        option: 'EC2KeyName',
        value: 'your-key-pair-name',
      },
  ],
  ...
}

**Comment by Roshdy** [comment]
Thanks for the quick response.
I noticed that after searching more today.
