### ISSUE TITLE
Copying .platform not supported

### ISSUE THREAD

**Issue by s7dhansh** [zodern/mup-aws-beanstalk#158]
I see that ebextensions are being copied but platform files are not. Here:
https://github.com/zodern/mup-aws-beanstalk/blob/0c557203cbab8932f68980fabe8404d20c68a3c4/src/prepare-bundle.js#L134

Kindly allow copying .platform files as well for nginx or any other related modifications.

**Comment by s7dhansh** [comment]
PR https://github.com/zodern/mup-aws-beanstalk/pull/160/files

**Comment by zodern** [comment]
This is available in mup-aws-beanstalk@0.7.1-beta.1
