### ISSUE TITLE
SSL approval email sent at each mup deploy

### ISSUE THREAD

**Issue by snajjar** [zodern/mup-aws-beanstalk#18]
Hello,

The SSL confirmation email seems to be sent every time you run `mup deploy`.
Isn't there any way to configure mup (or even better: to have mup do it automatically) to use the SSL certificate created by the previous deployment?

What happens between the moment you run `mup deploy` and the moment you manually confirm the SSL certificate? Is the website working, is this really zero downtime?

**Comment by zodern** [comment]
What does `mup beanstalk ssl` show?

**Comment by theodorDiaconu** [comment]
@snajjar did you solve the issue ?
