### ISSUE TITLE
502 Bad Gateway (nginx) How to properly assign ports?

### ISSUE THREAD

**Issue by cormip** [zodern/mup-aws-beanstalk#184]
Based on this line in the nginx error log:

2024/05/16 03:37:54 [error] 3477#3477: *1191 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.39.121, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "demo.myproduct.com"

I seem to be missing something about how the PORT assignments should be configured. The ELB is listening on ports 80 & 443 and properly routing all requests to the instance(s) on port 80 that nginx is apparently listening on. nginx then tries connecting to my upstream Meteor app for some reason on port 8081?! (when it's running on the default 3000)

I tried setting the Meteor PORT to 8081, but when I `mup reconfig` nginx then switched to looking for an Upstream Server on port 8039?!

Why is nginx even in the mix? The AWS ELB is already doing the load balancing and handling the SSL. So how should I be configuring mup & mup-aws-beanstalk to simply have the ELB communicate directly to my Meteor app's listening port? (or have nginx proxying on the proper ports)?

MY CONFIG ======================================

Meteor v2.16
mup v1.5.10
mup-aws-beanstalk v0.8.0

```javascript
module.exports = {
    app: {
        type: 'aws-beanstalk',
        name: 'MYPRODUCT',
        path: '../',
        minInstances: 1,
        instanceType: 'm6gd.medium',
        auth: {
            id: 'XXXXXXXXXXXXXXXXXXX',
            secret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        },
        sslDomains: ['demo.myproduct.com'],
        forceSSL: true,
        envName: 'myproduct-demo',
        oldVersions: 3,
        docker: {
            image: 'zodern/meteor:root'
        },
        buildOptions: {
            serverOnly: true,
            buildLocation: '../../myproduct-build'
        },
        env: {
            ROOT_URL: 'https://demo.myproduct.com',
            SESSION_TIMEOUT_SECONDS: 900,
            MONGO_URL: 'mongodb+srv://###############:###############@demo.xxxxxxxxx.mongodb.net/data?retryWrites=true&w=majority',
            MONGO_OPLOG_URL: 'mongodb+srv://###############:###############@demo.xxxxxxxxx.mongodb.net/local',
            MAIL_URL: 'smtp://app@XXXXX:XXXXXXXXXXXXXXXXXX@smtp.mailgun.org:587',
            METEOR_SIGTERM_GRACE_PERIOD_SECONDS: 30,
        }
    },
    plugins: ['mup-aws-beanstalk']
}
```

**Comment by paulincai** [comment]
Hi @cormip do you still need help for this?

**Comment by cormip** [comment]
I'd missed a somewhat cryptic error entry when reviewing `mup beanstalk logs`. My "production" REDIS server didn't have the same user permissions as my development REDIS server, so my app failed to start. Once I fixed the REDIS issue, the app started up and everything works.

**Comment by cormip** [comment]
I'd missed a somewhat cryptic error entry when reviewing `mup beanstalk logs`. My "production" REDIS server didn't have the same user permissions as my development REDIS server, so my app failed to start. Once I fixed the REDIS issue, the app started up and everything works.

BTW: 
nginx listens Port 80
Meteor app listens Port 8081 (upstream server)
ELB Health Check Port 8039
