### ISSUE TITLE
nginx and max packet size

### ISSUE THREAD

**Issue by dualbox** [zodern/mup-aws-beanstalk#19]
Hello,

On the current configuration, the deployed meteor app can't send/receive big requests (such as file uploads), because nginx will block them.
I had to fork mup-aws-beanstalk to add the following line to nginx.conf:

    client_max_body_size: 30M;

I'd rather use the original version of the plugin, is there a way to allow users to configure this?
Maybe we could override the proxy configuration somewhere in mup.js?

**Comment by pagesrichie** [comment]
Is this in the works?  Would def be awesome to be able to configure in standard mup.js configure file as opposed to forking and going inside

**Comment by snajjar** [comment]
Any news about this?

**Comment by jlichti** [comment]
We'd also be interested in a way to customize the nginx config.
Seeing some 1024 worker_connections are not enough errors

**Comment by mmueller1589** [comment]
I see lots of `1024 worker_connections are not enough` errors. Any idea how I can change the nginx config?

```
events {
	worker_connections 1024;
}
```

**Comment by etyp** [comment]
@zodern is there any way to get general support for .ebextensions? I think that'll help solve most problems like this + more.

**Comment by zodern** [comment]
Support for .ebextensions will be included in 0.7.0.
