### ISSUE TITLE
failing to deploy

### ISSUE THREAD

**Issue by ykptke** [zodern/mup-aws-beanstalk#27]
my config file; mup.js
![ss](https://user-images.githubusercontent.com/3853299/37648624-866a3844-2c40-11e8-8fe3-745ad5fc52c2.png)

mup deploy output:
`ConfigurationValidationException: Configuration validation exception: Invalid option value: 'null' (Namespace: 'aws:ec2:vpc', OptionName: 'Subnets'): Specify the subnets for the VPC for load balancer type application.`

**Comment by ramezrafla** [comment]
I am getting the same thing, seems to be a recent change in Beanstalk, anyone went through this process and found a solution?

**Comment by raphaelarias** [comment]
Have you tried to put the default VPC id and it's corresponding subnet ids?

Like:

`
 customBeanstalkConfig: [
      {
        namespace: 'aws:ec2:vpc',
        option: 'VPCId',
        value: 'vpc-axxxxxx'
      },
      {
        namespace: 'aws:ec2:vpc',
        option: 'Subnets',
        value: 'subnet-fxxxxxx'
      },
      {
        namespace: 'aws:ec2:vpc',
        option: 'ELBSubnets',
        value: 'subnet-dxxxxxx,subnet-cxxxxxx'
      },
...
`

**Comment by lmachens** [comment]
I get this error message when trying to deploy.
```
ConfigurationValidationException: Configuration validation exception: AWS Elastic Beanstalk could not communicate with Amazon EC2 to determine whether to create a custom security group for Elastic Load Balancing.
```
