### ISSUE TITLE
Idea: disable 50npm.sh

### ISSUE THREAD

**Issue by ramezrafla** [zodern/mup-aws-beanstalk#30]
Since we are not using the built-in nodejs and it sometimes causes issues downstream (or simply takes time to install), what if we added this to `node.config`:

`echo 'echo "=> Empty 50npm.sh"' > /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh`

**Comment by ramezrafla** [comment]
A more complete approach
```
echo 'echo "=> Empty"' > /opt/elasticbeanstalk/hooks/appdeploy/pre/40install_node.sh
echo 'echo "=> Empty"' > /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh
echo 'echo "=> Empty"' > /opt/elasticbeanstalk/hooks/configdeploy/pre/40install_node.sh
echo 'echo "=> Empty"' > /opt/elasticbeanstalk/hooks/configdeploy/pre/50npm.sh
```

**Comment by zodern** [comment]
There doesn't seem to be a way to do this anymore when using Amazon Linux 2.
