### ISSUE TITLE
Version deployment number

### ISSUE THREAD

**Issue by xonuzofa** [zodern/mup-aws-beanstalk#31]
Not sure what is going on, but say on aws elasticbeanstalk, I have two containers running version #70.  What is happening is, when I deploy a new version, it is attempting to deploy the new version as 70 and not 71.  

The first container (new container) builds fine and deploys no problem.  The second container (which is an upgrade of one of the old version containers) updates and then fails due to this error: Following services are not running: proxy.

About 15 minutes later, aws finally recognizes that it is the wrong version, then creates a fourth container, which now does have the new version #71, and then the upgrade on the second container works.  

Although this is actually building eventually and working, it takes 40-50 minutes to update my servers.  This happens every single time I try to deploy.

I have tried looking through the logs but nothing seems like its failing.  Feel like its more the mup script trying to push the wrong version number.  Not really sure.

Here is my console log:

=> Setting up
=> Ensuring IAM Roles and Instance Profiles are setup
Building App Bundle Locally
=> Archiving Bundle
  10% Archived
  20% Archived
  30% Archived
  40% Archived
  50% Archived
  60% Archived
  70% Archived
  80% Archived
  90% Archived
  100% Archived
=> Uploading bundle
  Uploaded 3%
  Uploaded 6%
  Uploaded 10%
  Uploaded 13%
  Uploaded 17%
  Uploaded 20%
  Uploaded 24%
  Uploaded 27%
  Uploaded 31%
  Uploaded 34%
  Uploaded 37%
  Uploaded 41%
  Uploaded 44%
  Uploaded 48%
  Uploaded 51%
  Uploaded 55%
  Uploaded 58%
  Uploaded 62%
  Uploaded 65%
  Uploaded 69%
  Uploaded 72%
  Uploaded 75%
  Uploaded 79%
  Uploaded 82%
  Uploaded 86%
  Uploaded 89%
  Uploaded 93%
  Uploaded 96%
  Uploaded 100%
  Finishing upload. This could take a couple minutes
=> Creating Version
=> Configuring Beanstalk Environment
  Updated Environment
=> Waiting for Beanstalk Environment to finish updating
  Env Event: Updating environment mup-env-****'s configuration settings.
  Env Event: Rolling with Additional Batch deployment policy enabled. Launching  a new batch of 1 additional instance(s).
  Env Event: Environment health has transitioned from Ok to Info. Configuration update in progress (running for 39 seconds).
  Env Event: Added instance [i-*******] to your environment.
  Env Event: Batch 1: 1 EC2 instance(s) [i-*******] launched. Deploying application version '70'.
  Env Event: Command execution completed on 1 of 3 instances in environment.
  Env Event: Batch 1: Completed application deployment.
  Env Event: Batch 2: Starting configuration deployment on instance(s) [i-*********].
  Env Event: Batch 2: Starting configuration deployment command execution.
  Env Event: Batch 2: Registering instance(s) with the load balancer and waiting for them to be healthy. 
  Env Event: Command execution completed on 2 of 3 instances in environment.
  Env Event: Batch 2: Completed configuration deployment command execution.
  Env Event: Environment health has transitioned from Info to Degraded. ELB processes are not healthy on 1 out of 3 instances. Configuration update in progress on 1 instance. 1 out of 3 instances completed (running for 9 minutes). ELB health is failing or not available for 1 out of 3 instances. Impaired services on 1 out of 3 instances.
  Env Event: Retrieving logs prior to instance(s) termination. Logs will be available for an hour in the environment management console and at ****.
  Env Event: During an aborted deployment, some instances may have deployed the new application version. To ensure all instances are running the same version, re-deploy the appropriate application version.
  Env Event: Failed to deploy configuration.
  Env Event: Instance id(s) 'i-**********' did not pass health check after command execution. Aborting the operation.
  Env Event: [Instance: i-************] Successfully finished bundling 18 log(s)
  Env Event: Excess instance(s) terminated.
  Env Event: Terminating excess instance(s): [i-*********].
  Env Event: The environment was reverted to the previous configuration setting.
=> Deploying new version
=> Waiting for Beanstalk Environment to finish updating
  Env Event: Rolling with Additional Batch deployment policy enabled. Launching  a new batch of 1 additional instance(s).
  Env Event: Removed instance [i-***********] from your environment.
  Env Event: Added instance [i-*********] to your environment.
  Env Event: Batch 1: 1 EC2 instance(s) [i-***********] launched. Deploying application version '71'.
  Env Event: Command execution completed on 1 of 3 instances in environment.
  Env Event: Batch 1: Completed application deployment.
  Env Event: Batch 2: Starting application deployment on instance(s) [i-**************].
  Env Event: Deploying new version to instance(s).
d  Env Event: Batch 2: Starting application deployment command execution.
Env Event: Batch 2: Registering instance(s) with the load balancer and waiting for them to be healthy. 
  Env Event: Command execution completed on 2 of 3 instances in environment.
  Env Event: Batch 2: Completed application deployment command execution.
  Env Event: Environment health has transitioned from Degraded to Info. Application update in progress on 1 instance. 1 out of 3 instances completed (running for 9 minutes).
  Env Event: Batch 2: Completed application deployment.
  Env Event: Terminating excess instance(s): [i-*******].
  Env Event: Excess instance(s) terminated.
App is running at mup-env-*******
=> Finding old versions
=> Removing old versions
=> Checking Certificate Status
Certificate has been issued
=> Updating Beanstalk SSL Config

**Comment by xonuzofa** [comment]
Actually realizing that I have two computers updating this EB.  1 computer does not have this problem, the other does.  Both same mup.js settings, any ideas?

**Comment by mike-weng** [comment]
> Actually realizing that I have two computers updating this EB. 1 computer does not have this problem, the other does. Both same mup.js settings, any ideas?

Did you end up finding a solution?

**Comment by zodern** [comment]
This should be fix in 0.7: #142
