### ISSUE TITLE
ROOT_URL where to get&

### ISSUE THREAD

**Issue by xolab** [zodern/mup-aws-beanstalk#33]
Hey, Zodem!

Prompt, please, where to get ROOT_URL for mup.json? Оr need to pre-configure in AWS, ES2, Elastic Beanstalk or oth. to get ROOT_URL?

Thanks, Evgeny

**Comment by csKangGdcomm** [comment]
On getting-started.md, there is no mention about where to get the url.
you can check ROOT_URL at http://meteor-up.com/docs.html#example-configs
from above doc, ROOT_URL means Metoer's ROOT_URL and
I think it doesn't make sense that before deploying by elasticbeanstalk, there is no URL.
The way I am using is that first deploy the app with fake URL and then I can get the URL from elasticbeanstalk, then I redeploy with the url ... 
is it right scenario?
