### ISSUE TITLE
Genius package, thanks!

### ISSUE THREAD

**Issue by satyavh** [zodern/mup-aws-beanstalk#40]
I just wanted to say, thank you for creating this amazing MUP plugin 🚀

Imo this can really compete with Galaxy and makes deploying auto-scaling Meteor so freakin' easy. Although I'm not 100% sure yet how the cost will compare :-)

If I can make a donation somewhere, or perhaps write an article about it (this needs more exposure really!) let me know.

**Comment by pagesrichie** [comment]
@satyavh Were you able to get this working?

**Comment by zodern** [comment]
Thanks @satyavh!
