### ISSUE TITLE
Cron running in multiple server

### ISSUE THREAD

**Issue by MrSpark2591** [zodern/mup-aws-beanstalk#41]
Thanks for great this great project :) 
I am starting to use it for deploying my application. but i had a question which i want to ask.
For running cron jobs i am using [sync-cron](https://github.com/percolatestudio/meteor-synced-cron). just wanted to ask that as galaxy manages that cron run only in one of the container. can this be achieved same here?

**Comment by zodern** [comment]
Yes, it will work correctly. `sync-cron` uses a collection in MongoDB to only run the job on one server, which  isn't reliant on a specific PaaS or deployment tool.
