### ISSUE TITLE
Node Versioning

### ISSUE THREAD

**Issue by PolybitSol** [zodern/mup-aws-beanstalk#45]
**Meteor Version:** 1.6.0.1
**Node Version:** 8.9.3

When I deploy my application via MUP to AWS, it enumerates the wrong version of Node, setting the environment to an outdated version 6.13.1 instead, causing the application to crash with the `Object.getOwnPropertyDescriptors is not a function` bug.

**Comment by zodern** [comment]
Which version of this plugin are you using?

**Comment by PolybitSol** [comment]
The latest version from NPM I believe, v0.5.1

**Comment by zodern** [comment]
Which node version is shown when you run `mup logs`?

**Comment by PolybitSol** [comment]
So I've done some playing around, and on my last redeploy it finally shows the correct version when running the `mup logs` command (v8.9.3), however visting the Elastic Beanstalk environment's URL fails to resolve even though the environment is healthy. Do you have any idea why this might be? Viewing the `mup logs` doesn't indicate any errors.

**Comment by PolybitSol** [comment]
Just as an update, after reviewing the load balancing a route a bit more, it appears the load balancing & security groups weren't properly configured to allow HTTPs. Adding the appropriate rules and listeners fixed this.

**Comment by PolybitSol** [comment]
I just had issue after deploying a new update where the listener & security policy were reset again to disallow HTTPS. Is there a fix for this, so I don't have to change it before every patch?

I have ``forceSSL: true`` set and the correct ``sslDomains`` set, though ``ROOTDOMAIN`` uses the http:// variant, could this be the cause? I can't think of what else to change in the config

**Comment by zodern** [comment]
Go to the environment in the Elastic Beanstalk console, click Configuration on the left, and click Load balancer. Is there a row in the table for port 443 with the correct ssl certificate?

**Comment by zodern** [comment]
Using the wrong node version is fixed in #142 - it no longer matters what version of node beanstalk is configured to use.
