### ISSUE TITLE
Enhancement - Rolling Deploys with CDN - Target Groups?

### ISSUE THREAD

**Issue by jlichti** [zodern/mup-aws-beanstalk#51]
Thanks for this great package!

We use a CDN (CloudFront) to deliver our bundle and static asset and for a rolling deployment there could be an issue with the load balancer passing to older version. On our current digital ocean setup I have a staging server I deploy to first to serve the static content and then snapshot to scale up manually.

Galaxy seems to have this solved using a query string.
https://galaxy-guide.meteor.com/cdn.html

I'm new to AWS and the application load balancer but I'm wondering if target groups and path based forwarding rules could work in the same way.

As a workaround I set the deployment to immutable so they will all cut over at the same time
```
{
  namespace: 'aws:elasticbeanstalk:command',
  option: 'DeploymentPolicy',
  value: 'Immutable'
 }
```

**Comment by pagesrichie** [comment]
I'm having difficulty grabbing the latest version, it crashes my website upon load in browser as it cannot find the bottom meteor script (random hash .js that ends with ?meteor_js_resource=true) .. ends up with 504 ERROR
The request could not be satisfied. 

I tried your workaround as well.  I'm also using https://github.com/Nitrolabs/meteor-cdn plugin.  

Don't know what to do to move forward with fixing the cdn..

**Comment by zodern** [comment]
The [mup-cloud-front](https://github.com/zodern/mup-cloud-front) plugin was designed to work correctly with rolling deploys.
