### ISSUE TITLE
Using basic settings getting "Env Event: Environment health has transitioned from Severe to Degraded."

### ISSUE THREAD

**Issue by pagesrichie** [zodern/mup-aws-beanstalk#53]
I just have basic default settings set in mup.js

  Env Event: Environment health has transitioned from Severe to Degraded. 100.0 % of the requests are failing with HTTP 5xx. ELB processes are not healthy on 1 out of 2 instances. Configuration update in progress on 1 instance. 0 out of 2 instances completed (running for 3 minutes). ELB health is failing or not available for 1 out of 2 instances.
  Env Event: Environment health has transitioned from Degraded to Severe. 50.0 % of the requests are failing with HTTP 5xx. ELB processes are not healthy on 1 out of 2 instances. Configuration update in progress on 1 instance. 0 out of 2 instances completed (running for 4 minutes). ELB health is failing or not available for 1 out of 2 instances.

What may be causing this?

**Comment by gabdsg** [comment]
I have the same problem

**Comment by roblingle** [comment]
@pagesrichie Did you get this resolved? If so, any recollection? 
Curious why it was closed and I'm currently stuck here.
