### ISSUE TITLE
[feat] Custom build instructions

### ISSUE THREAD

**Issue by jorgeer** [zodern/mup-aws-beanstalk#61]
I've been a fan of the "docker.buildInstructions" options in mup, and would like to have the same option in some way when deploying to ELB. 

I have implemented the feature in a fork, so my question is if this is wanted by others as well? Maybe there is a good reason this is not already implemented and there are some things I have not considered also.

If this is wanted, I will open a PR for it.

**Comment by zodern** [comment]
I think this is covered by #72

**Comment by 1tac11** [comment]
Hi, is there any update on this matter? Can buildinstructions be used in aws EBS? Greets
