### ISSUE TITLE
Rate Limiting in Nginx Config for Security

### ISSUE THREAD

**Issue by convexset** [zodern/mup-aws-beanstalk#67]
Hi,

Any chance of adding some [rate limiting to the nginx config](https://www.nginx.com/blog/rate-limiting-nginx/) for first-level security against web socket connection attacks?

See, for instance: http://www.petecorey.com/blog/2016/05/16/the-missing-link-in-meteors-rate-limiter/

> Rate limiting on the network level means that abusively excessive requests to the /websocket HTTP endpoint will fail, which stops the WebSocket handshake process dead in its tracks, killing the connection before it hits your Meteor server.

**Comment by zodern** [comment]
It is unlikely this will be added, but I am planning to look into ways to allow customizing the nginx config.
