### ISSUE TITLE
High memory usage by health-check.js after 4-5 hours

### ISSUE THREAD

**Issue by s7dhansh** [zodern/mup-aws-beanstalk#73]
Somehow it affects only one of my 3 deployments using this plugin. But this effect is consistent on the one deployment. Every 4-5 hours the `health-check.js` memory usage shoots up. Once I kill it, the server is fine and app behaves normally. Can someone please help?

**Comment by jimrandomh** [comment]
I'm debugging this issue right now. `health-check.js` (https://github.com/zodern/mup-aws-beanstalk/blob/master/src/assets/health-check.js) doesn't close its response correctly, which causes it to leak a file handle after each request. (You can see the leaked file handles in `lsof`.) Eventually enough of them accumulate to bring down the server.

**Comment by jimrandomh** [comment]
https://github.com/zodern/mup-aws-beanstalk/pull/89

**Comment by jimrandomh** [comment]
This bug is fixed by the linked PR, but there hasn't been a release. If you need a fix, you can switch to my fork, https://github.com/jimrandomh/mup-aws-beanstalk , but that fork won't ever have anything on it except that one fix.

**Comment by elie222** [comment]
I believe this has now been merged and published in 0.63 and we can close this issue:
https://github.com/zodern/mup-aws-beanstalk/pull/89
