### ISSUE TITLE
AWS Beanstalk platform upgrade

### ISSUE THREAD

**Issue by snajjar** [zodern/mup-aws-beanstalk#75]
Hello,

It seems AWS is decommissioning the Linux/4.4.4 version that is actually used on mup-aws-beanswtalk, the new platform available is Linux/4.8.1.

Could we update mup-aws-beanstalk to deploy with the new platform?

**Comment by zodern** [comment]
It is possible to update the platform version using the AWS console. I could add a command to update it, but I'm not sure if it is needed.
