### ISSUE TITLE
Error on first deploy

### ISSUE THREAD

**Issue by katusiky** [zodern/mup-aws-beanstalk#8]
`[TypeError: Cannot read property 'charCodeAt' of undefined]`

![selection_233](https://user-images.githubusercontent.com/15224507/34632135-cdec1824-f241-11e7-9a32-e364833d56f5.png)

**Comment by katusiky** [comment]
sorry! my error!

**Comment by zodern** [comment]
The docs are fixed. I also modified a [script](https://github.com/zodern/mup-aws-beanstalk/blob/master/tests/validate-docs.js) from meteor up that validates every example config to help prevent this from happening again.
