### ISSUE TITLE
InvalidParameterValue: Environment named "server-name" is in an invalid state for this operation. Must be Ready.

### ISSUE THREAD

**Issue by pagesrichie** [zodern/mup-aws-beanstalk#80]
Running into these issues after stopping a server using "mup stop" and then trying to restart it later on "InvalidParameterValue: Environment named "mup-env-server-name" is in an invalid state for this operation. Must be Ready."  

I checked my EC2 instances, they all completely disappeared and then a few days later, just "mup deploy" , and ran across this invalid state for operation, must be ready error.  Tried to mup deploy 4 times, waited a while, and then does the following:

" 
...
Uploaded 96%
  Uploaded 97%
  Uploaded 99%
  Uploaded 100%
  Finishing upload. This could take a couple minutes
=> Creating Version
=> Configuring Beanstalk Environment
InvalidParameterValue: Environment named mup-env-server-name is in an invalid state for this operation. Must be Ready.
"

**Comment by zodern** [comment]
After running `mup stop`, the environment state becomes grey. Running `mup start` will change it back to ready.

**Comment by pagesrichie** [comment]
I tried "mup start" , and all it does is "Waiting for Beanstalk Environment to be green" for hours... does nothing else.

mup start
=> Starting App
=> Waiting for Beanstalk Environment to be green

(Just stuck on that..)

**Comment by zodern** [comment]
If you go to `https://console.aws.amazon.com/elasticbeanstalk/home` and select the environment, it should give you more information. What is the current state? What are the last few events?

**Comment by pagesrichie** [comment]
Environment tier:
Web Server
Platform:
Node.js running on 64bit Amazon Linux/4.7.0
Running versions:
1
Last modified:
2018-11-26 20:50:43 UTC-0800

Health status:
Suspended
Health
Grey
Causes

No recent events

**Comment by pagesrichie** [comment]
InvalidParameterValue: Environment named  "mup-env-server-name" is in an invalid state for this operation. Must be Ready.
    at Request.extractError (/Users/r/.nvm/versions/node/v8.3.0/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/Users/r/.nvm/versions/node/v8.3.0/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/r/.nvm/versions/node/v8.3.0/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

**Comment by zodern** [comment]
If anyone else encounters an environment being in a suspended state again we can re-open this issue or create a new one.
