### ISSUE TITLE
mup consulting?

### ISSUE THREAD

**Issue by zzaacchh** [zodern/mup-aws-beanstalk#92]
I am a part of a team that maintains about 8 internal meteor applications, each which currently get deployed to AWS Elastic Beanstalk with a common script that was built by the team.  I'd love to move to mup, for a host of reasons, but it wouldn't be trivial, as our deploys will require custom .ebextensions (which appear to be supported by an unmerged PR) and customization of the Beanstalk Application name (which I imagine would be relatively easy to wire up).  Does anyone on the core mup team do any consulting work for situations like this?

**Comment by zzaacchh** [comment]
@zodern  -- sorry, meant to tag you on the previous message.

**Comment by joaocarloscabral** [comment]
I'm using .ebextensions by a custom npm packge.
Check this https://github.com/zodern/mup-aws-beanstalk/pulls

**Comment by zodern** [comment]
Support for `.ebextensions` will be in mup 0.7 (#142). If you want consulting for anything else you can contact me at zodern@montiapm.com. There is also a tier for sponsoring me that provides support (https://github.com/sponsors/zodern).
