### ISSUE TITLE
https forwarding discards URL parameters

### ISSUE THREAD

**Issue by jimrandomh** [zodern/mup-aws-beanstalk#94]
In https://github.com/zodern/mup-aws-beanstalk/blob/master/src/assets/nginx.yaml there is a bit of server configuration which forwards http URLs to https URLs if the `forceSSL` option is set. Unfortunately, the forwarding is incorrect; it discards URL parameters, so a link to (for example) `http://www.example.com/page?someParam=1&someOtherParam=2` forwards to `https://www.example.com/page` without the parameters.

**Comment by zodern** [comment]
I'm not able to reproduce.
